name: SimplePopUps
version: :v
api: 
- 1.3.1
- 1.4.0
- 1.4.1
- 2.0.0

author: _Lion
main: _Lion\SimplePopUps\Main

commands:
 pop-up:
  description: "'say' a popup"
  usage: "/pop-up <msg>"
  permission: "simplepopups.command.popup"
 tip:
  description: "'say' a tip"
  usage: "/tip <msg>"
  permission: "simplepopups.command.tip"

permissions:
 simplepopups:
  default: op
  description: "algo"
  children:
   simplepopups.command:
    default: op
    description: "commands"
    children:
     simplepopups.command.popup:
      default: op
      description: "popup"
      children:
        simplepopups.command.tip:
        default: op
        description: "tip"